# config.yaml

usage_parameters:
  input_image_path: "C:/Users/anlun/OneDrive/Pictures/bella/Raw"
  output_image_path: "C:/Users/anlun/OneDrive/Pictures/bella/Segmented"
  model_path: "./models/sam2.1_b.pt"
  verbosity: 2
  device: "cuda:0"
  visualization_size: 800
